### ISSUE TITLE
Projection support

### ISSUE THREAD

**Issue by simlevesque** [edwardhotchkiss/mongoose-paginate#100]
Hi, I'd like to know if someone could add projection support to this plugin, if not I'll eventually make a pull request to add it in the next month. Thank you.

**Comment by Jokero** [comment]
It exists. See `select` option https://github.com/edwardhotchkiss/mongoose-paginate#modelpaginatequery-options-callback

**Comment by simlevesque** [comment]
Oh well I think it's stupid that Mongoose changed the name of projection into select...
