### ISSUE TITLE
populate fields selection 

### ISSUE THREAD

**Issue by pankug** [edwardhotchkiss/mongoose-paginate#101]
Hey,
Using mongoose-paginator for pagination. while using with populate method how can i select the fields i want to from populate fields.

userContent.paginate({},{lean:true,populate:['user_id']}).

I want to select fields from populated collection

**Comment by Jokero** [comment]
Hi! You can specify object with options for `populate` http://mongoosejs.com/docs/api.html#document_Document-populate

**Comment by pankug** [comment]
Thanks. For help @Jokero
