### ISSUE TITLE
Setting the sort key for options does not work

### ISSUE THREAD

**Issue by mitchellporter** [edwardhotchkiss/mongoose-paginate#102]
I just tested this multiple times using `v5.0.0` for 2 different fields, one is a `Date` and the other is a `Number`. I've tried the string sort syntax and using an object, neither of these work at all for me.

Some example code:

```
var options = {};
options['sort'] = { created_at: -1 }; // Date field
```

```
var options = {};
options['sort'] = { random_number_field: -1 }; // Number field
```

```
var options = {};
options['sort'] = 'created_at -1'; // String sorting
```

None of these have any effect for me. The data is pulled down in the same order every time, and I have already verified that both fields have varying data, which means I should be able to change the order they arrive in if the sort functionality is working correctly.

**Comment by Jokero** [comment]
It should work, there is test for it https://github.com/edwardhotchkiss/mongoose-paginate/blob/v5.0.0/tests/index.js#L145-L149:

``` js
it('with sort', function() {
    return Book.paginate({}, { sort: { date: -1 } }).then(function(result) {
        expect(result.docs[0].title).to.equal('Book #100');
    });
});
```

Does `sort` work with `mongoose` for you?

**Comment by mitchellporter** [comment]
@Jokero I don't have much experience with testing so didn't even look at the tests, but thank you for the response.  I'm going to retest and will also try a vanilla mongoose sort as well. Will report back with the results soon.

**Comment by mitchellporter** [comment]
Took me awhile to get back to this but after further testing I realized it was a mistake I was making. Sorting by date works just fine.

**Comment by abalsekar** [comment]
The sort option was called sortBy until v. 5.0.0 - this was the mistake I made.
