### ISSUE TITLE
Nested Populate does not working

### ISSUE THREAD

**Issue by duylddev** [edwardhotchkiss/mongoose-paginate#149]
My bad, i fix it.
Sorry :(

**Comment by federicosan** [comment]
for anyone that gets here, the way to use populate in the options object in paginate is by declaring a property populate as in the example but to get multiple paths you need to set an array for example , Suppose you have a blog with articles that have reviews., and you use a  schema that supports versions, so no edition is deleted, and you are always swapping the current version to an old article versions array.

your schmea looks like this:

current {
property1:
...
propertyn:
}
old: [{
property1:
...
propertyn:
} ]

you can populate all the old versions field reviews and the array reviews property in current with just this populate options 

var query = {};
var options = {
  populate: [{path: 'current.reviews'}, {path:'old.reviews'}]
  lean: true,
  offset: 20, 
  limit: 10
};

Blog.paginate(query, options).then(function(result) {
  // ...
});
