### ISSUE TITLE
DeprecationWarning 

### ISSUE THREAD

**Issue by ashadnasim52** [edwardhotchkiss/mongoose-paginate#160]
> DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

**Comment by dyarleniber** [comment]
This issue has already been registered.

I recommend you use the mongoose-paginate-v2 package.

**Comment by ashadnasim52** [comment]
thanks for response

**Comment by a-wf** [comment]
Hello, @dyarleniber   
what is the difference between those two packages (mongoose-paginate vs mongoose-paginate-v2) ?
