### ISSUE TITLE
Mongoose 5.8.0 compatibility

### ISSUE THREAD

**Issue by adriano-di-giovanni** [edwardhotchkiss/mongoose-paginate#162]
Is `mongoose-paginate` compatible with `mongoose@5.8.0`?

**Comment by StereoPT** [comment]
I'm using it with `mongoose@5.8.0` and it works fine. However it gives me a Deprecation Warning for collection.count

**Comment by MickL** [comment]
Works fine on 5.12.7 but deprecation warning. You may close this issue @adriano-di-giovanni
