### ISSUE TITLE
how to define what keys I need to return?

### ISSUE THREAD

**Issue by maggie03230** [edwardhotchkiss/mongoose-paginate#30]
When I'm using mongoose, I can find and return the keys I need, just like: myModel.find(null,{name:true})
and the data come back will be[ {_id:xxx,name:xxx},{_id:yyy,name:yyy}] ……just like that.
can mongoose-paginate also return specific keys I need?

**Comment by niftylettuce** [comment]
You mean `.select` like querying?  Sure just pass it as options.

**Comment by ccnokes** [comment]
I've been trying to pass select options like so:

```javascript
	Article.paginate(
		{ 
			status: 'active'
		}, 
		{
			select: 'title teaser createdDate status _id slug',
			page: page, 
			limit: limit,
			sortBy: {
				createdDate: -1
			}
		}, 
		paginateCb
	);
```

That doesn't seem to be working and I've tried a few variations on the select property, such as `{title:-1}`. Am I missing something?

**Comment by ccnokes** [comment]
Oh just kidding, just got it working using the `columns` property like so:

```javascript
	Article.paginate(
		{ 
			status: 'active'
		}, 
		{
			columns: 'title teaser createdDate status _id slug',
			page: page, 
			limit: limit,
			sortBy: {
				createdDate: -1
			}
		}, 
		paginateCb
	);
```
