### ISSUE TITLE
exclude field

### ISSUE THREAD

**Issue by fabiusss** [edwardhotchkiss/mongoose-paginate#38]
How exclude field with this plugin?
I want to exclude fields salt and hashedPassword
    User.find(query,'-salt -hashedPassword',function.............

**Comment by CrackerakiUA** [comment]
I need this too, also i thinking if it's possible to exclude from populated object.

**Comment by niftylettuce** [comment]
Is this still an issue?

**Comment by CrackerakiUA** [comment]
Watch is good, but exclude it's kinda better :)
