### ISSUE TITLE
populate broken in 3.1.4

### ISSUE THREAD

**Issue by hbj** [edwardhotchkiss/mongoose-paginate#40]
Version `3.1.4` breaks populate definitions that use objects, e.g.

```js
[{path: user, select: 'firstname lastname'}, {path: address, select: 'street'}]
```

**Comment by niftylettuce** [comment]
thanks @hbj will roll back, one moment

**Comment by niftylettuce** [comment]
Okay I have deleted 3.1.4 and rolled back to 3.1.3.

**Comment by niftylettuce** [comment]
See v3.1.5 and updated Readme documentation here
