### ISSUE TITLE
3.1.6 from 3.1.3

### ISSUE THREAD

**Issue by elgubenis** [edwardhotchkiss/mongoose-paginate#45]
shouldnt that have been a breaking change? all my paginate implementations didnt work anymore when i updated, i downgraded to 3.1.3 and everything was fine, i thought when the last number changes that there would be no breaking change of the api.

**Comment by niftylettuce** [comment]
Yes I need to increment the major, sorry about that, I will deprecate all but 3.1.3 and then release 4.0.0.  Thanks for the heads up again @elgubenis

**Comment by niftylettuce** [comment]
Done, published `v4.0.0` to NPM and unpublished 3.1.4-3.1.6

**Comment by elgubenis** [comment]
awesome :+1:  thanks!

**Comment by Apercu** [comment]
I've been updated to *3.1.6* today using the `^3.1.3` pattern, please make sure to increment the major or at least minor when doing big refactors like that, I'm sure I'm not the only one who will get impacted by this

**Comment by niftylettuce** [comment]
I unpublished, it shouldn't be available in NPM.
