### ISSUE TITLE
Update History.md

### ISSUE THREAD

**Issue by simison** [edwardhotchkiss/mongoose-paginate#46]
Would love to see changes for 4.x

https://github.com/edwardhotchkiss/mongoose-paginate/blob/master/History.md

Thanks!

**Comment by Kaylors** [comment]
On a similar note, providing a list of changed might have prevented me some grief. I blame npm for updating the package without notifying me but a history here would  have really helped quickly figure the API changes and not have me refactor code in so many places.

**Comment by edwardhotchkiss** [comment]
Hey @Kaylors & @simison - please see the revised CHANGELOG.md and feel free to do a PR for v4.0.0 etc with sweeping changes. I've been extremely busy and will try and keep everyone happy :)

**Comment by niftylettuce** [comment]
@simison or @Kaylors can either of you do this for us?

**Comment by edwardhotchkiss** [comment]
The CHANGELOG is up to date.
