### ISSUE TITLE
Aggregation Support?

### ISSUE THREAD

**Issue by freezy** [edwardhotchkiss/mongoose-paginate#48]
It would be neat if [aggregations](http://mongoosejs.com/docs/api.html#aggregate-js) would be supported as well.

However, API-wise I'm not sure if that would mean an additional method or just another option, where the actual query would either be ignored or interpreted as an aggregation pipeline.

Thoughts?

**Comment by Decad** [comment]
+1 this would be really useful

**Comment by niftylettuce** [comment]
@freezy @Decad pull requests welcome!

**Comment by freezy** [comment]
The problem with aggregations is that there is no automatic `count` operation, so I doubt a generic solution such as the current one would be possible.
