### ISSUE TITLE
Searching with Weights

### ISSUE THREAD

**Issue by dtrikannad** [edwardhotchkiss/mongoose-paginate#55]
I am trying to apply the following query to the paginate function, but don't think it works. 

    var docItems = require('../models/docItems.js');
    docItems.find(
            {$text: {$search: req.query.searchString}}
            , {score: {$meta: "textScore"}}
        )
            .sort({ score : { $meta : 'textScore' } })
            .exec(function(err, results) {
    
                return next(err, results);
            });

the `, {score: {$meta: "textScore"}}` line is what is missing in the following code: 

    docItems.paginate(
        {$text: {$search: req.query.searchString}, score: {$meta: "textScore"}},
        { page: 1, sortBy: { score : { $meta : 'textScore' } }},
        function(err, results, pageCount, itemCount) {
            console.log('hello');
            return next(err, results, pageCount, itemCount);
        });

Is there a way to submit the score meta line? what am i missing?

Thank you.

**Comment by edwardhotchkiss** [comment]
I'm looking at rewriting the plugin this weekend in ES6 with an updated test suite for some of MongoDB/Mongoose's *newer* (this is an old lib after all) features and full coverage.

**Comment by edwardhotchkiss** [comment]
@dtrikannad Would you mind writing a test (possibly named `test/weighted.test.js`?); then I can make it work. Thanks.

**Comment by josh-g3** [comment]
What was the outcome of this?
