### ISSUE TITLE
Rename sortBy to sort

### ISSUE THREAD

**Issue by surdu** [edwardhotchkiss/mongoose-paginate#60]
Chased a bug for an hour, then I realised that this library has a different name for sort (`sortBy`) than I'm used to from mongoose (`sort`).

In order to prevent backward incompatibility with older paginate versions, you could make `sortBy` an alias for `sort` that will additionally throw a deprecation warning in the console.

If it's ok with you, I could implement this myself.

**Comment by edwardhotchkiss** [comment]
Feel free to do a PR :) Sounds great, thanks @surdu.
