### ISSUE TITLE
TypeError: undefined is not a function  at Function.paginate 

### ISSUE THREAD

**Issue by ajbraus** [edwardhotchkiss/mongoose-paginate#71]
TypeError: undefined is not a function at Function.paginate (/mongoose-paginate/index.js:20:22)

**Comment by Jokero** [comment]
You use nodejs < 4.0.0? `mongoose-paginate` 5.0.0 works only with Node.js >= 4.0.0 and Mongoose >= 4.0.0

**Comment by ajbraus** [comment]
node 4.1.1 already installed, 
"mongoose": "^4.1.10",
"mongoose-paginate": "^5.0.0",

**Comment by ajbraus** [comment]
I tried the Model.statics.paginate = mongoosePaginate.paginate() and that seems to work better, but all the ES6 special sauce you used is breaking. Object.assign and this.count, etc.

**Comment by ajbraus** [comment]
ohhhh node <4.0.0 ok weird. I guess i can downgrade.

**Comment by Jokero** [comment]
`console.log(process.version)`?

**Comment by ajbraus** [comment]
`console.log(process.version)` => v0.12.6

**Comment by Jokero** [comment]
`0.12.6` < `4.0.0` :smiley: So you should install new version of nodejs (>= 4.0.0)

**Comment by ajbraus** [comment]
so node should be greater than 4.0.0 ok.

**Comment by ajbraus** [comment]
Thx! Happy Holidays~

**Comment by Jokero** [comment]
Good luck!

**Comment by ajbraus** [comment]
Oops, more problems:

`TypeError: undefined is not a function
   at /Users/Penelope/dev/ga-qa/resources/questions.js:13:14
   at Layer.handle [as handle_request] (/Users/Penelope/dev/ga-qa/node_modules/express/lib/router/layer.js:95:5)`

**Comment by ajbraus** [comment]
now I'm at node 4.1.0

**Comment by Jokero** [comment]
Do you remove `Model.statics.paginate = mongoosePaginate.paginate()`? Show your code

**Comment by ajbraus** [comment]
got it working! I'm nutz, sorry. Just the version problem.
