### ISSUE TITLE
MongoError: Failed to parse 'limit' field must be numeric

### ISSUE THREAD

**Issue by wiesys** [edwardhotchkiss/mongoose-paginate#72]
Kind of "straight forward" that 'limit' field must be numeric, but in scenario that I got limit from `req.query.limit` in Express it brings in some, in my opinion, unnecessary "string to number conversion code".

In version 4 everything worked also if `limit` was string. Not realy a bug, but maybe you can bring this string conversion back in mongoose-paginate core?

**Comment by Jokero** [comment]
Nothing changed :) `limit` is passed without any conversion.

v4.0.1:
```js
var resultsPerPage = options.limit || 10;
// ...
query.skip(skipFrom).limit(resultsPerPage);
```

v5.0.0:
```js
var limit = options.hasOwnProperty('limit') ? options.limit : 10;
// ...
var docsQuery = this.find(query)
                    .select(select)
                    .sort(sort)
                    .skip(skip)
                    .limit(limit)
                    .lean(lean);
```

And I think you should validate request parameters

**Comment by edwardhotchkiss** [comment]
Limit is an integer unless you pass otherwise. Definitely validate request params!

**Comment by anilbhanushali** [comment]
This was not an issue in earlier version of mongodb(2.x) it is only when i switched to 3.2.1

**Comment by markstos** [comment]
I saw the same behavior change when upgrading Mongoose from version 3.8 to 4.13.  Before, I could pass strings to `skip` and `limit`. After the upgrade, a parse error was thrown. In any case, the behavior change seems unrelated to this pagination plugin.

**Comment by wangjiafenghw** [comment]
like cmd talk to you, the value of "limit" must be a number value, my code alse have this bug ,i just add `parseInt()` ,like this   `query.limit(parseInt(param.pageSize))`,, it become work

**Comment by wangjiafenghw** [comment]
> like cmd talk to you, the value of "limit" must be a number value, my code alse have this bug ,i just add `parseInt()` ,like this `query.limit(parseInt(param.pageSize))`,, it become work

* - `limit` {Number} max number of documents       "version": "5.3.17-pre",
