### ISSUE TITLE
Extend mongoose query class?

### ISSUE THREAD

**Issue by zekenie** [edwardhotchkiss/mongoose-paginate#74]
I'm having an issue where I sometimes want to paginate, and sometimes I want to find all. It becomes cumbersome because I have to specify population, select, etc in two different formats.

```
if(iWantToPaginate) {
  return myModel.paginate(query, { populate: 'foo', select: 'bar' });
else {
  return myModel.find(query).populate('foo').select('bar')
}
```

How simple would it be to have the populate method extend the mongoose query prototype:

`myModel.find(query).populate('foo').select('bar').paginate({ page: 4 })`

?

Possibly of note: https://github.com/Automattic/mongoose/issues/2696

**Comment by zekenie** [comment]
I think something like this would work:

```js
'use strict';
const mongoose = require('mongoose');
const Promise = require('bluebird');
mongoose.Query.prototype.paginate = function(page, perPage) {
  page = page || 1;
  page--;
  const limit = perPage || 10;
  return Promise.props({
    total: this.model.count(this.getQuery()),
    limit, 
    page,
    docs: this.limit(limit).skip(page*limit)
  });
}
```

**Comment by zekenie** [comment]
I suppose the only issue is this would make people think that the method returns a query object when in fact it returns a promise.

**Comment by edwardhotchkiss** [comment]
@zekenie thinking about it ... just ES6 promise ...

**Comment by edwardhotchkiss** [comment]
@zekenie check out the just completed ES6 branch. Let me know your thoughts and if you'd like this integrated :+1:

**Comment by latitudehopper** [comment]
This looks awesome, is it possible now?

**Comment by lesterzone** [comment]
I think it's possible. :joy: (node v6 is out )
I have a question about the shipping version of mongoose against installed on each project, It will cause conflict? Due the specific version of mongoose required by some projects.

BTW, mongoose dependency is on `devDependencies`, is that expected?
