### ISSUE TITLE
Sorting/Searching populated documents as well as paginate

### ISSUE THREAD

**Issue by dolanmiu** [edwardhotchkiss/mongoose-paginate#75]
I have an ```Item``` collection which shows details about the items gets updated very frequently with different prices.

I also have an ```InventoryItem``` collection which represents a real item which references then Item collection. It will have its ```assetId```, who owns it, which bot its in etc.

Now I am making a store which I will stock all these ```InventoryItem```s in.

Here is the Schemas for ```Item``` and ```InventoryItem```:

```Item``` Schema:

    var ItemSchema = new mongoose.Schema({
        item: {
            marketName: String,
            model: String,
            set: String,
            exterior: String
        },
        price: {
            currency: String,
            custom: Number,
            steam: Number
        },
        quantity: Number,
        blacklist: {
            type: Boolean,
            default: false
        },
        custom: Boolean,
        iconUrl: String
    });

```InventoryItem``` Schema:

    var InventoryItemSchema = new mongoose.Schema({
        item: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Item'
        },
        assetId: String,
        location: String,
        bot: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Bot'
        },
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        }
    });

Now the problem arises when I try and search ```InventoryItem``` by ```name```, or sort by ```price```, because ```name``` and ```price``` is inside the ```Item``` collection.

I can't copy ```price``` from an ```Item``` into ```InventoryItem``` because as I said, the ```price``` updates frequently, and there will be multiple of the same ```Item```.

Population is a solution, but I would need to sort/find after populating, which I do not believe is possible.

The store will have potentially thousands of items, so the data needs to be paginated. I am using ```mongoose-paginate``` to deal with that.

How would I do this? I am very stumped.

**Comment by LiorRabin** [comment]
Hi,
I'm facing the same issue. Did you find a solution ?

**Comment by dolanmiu** [comment]
@LiorRabin I have neve found a solution to this; this is a limitation of MongoDB I believe :(

**Comment by LiorRabin** [comment]
@dolanmiu yeah...that's what I understand as well, too bad :(

**Comment by crossRT** [comment]
@dolanmiu I having the same issue now.
Have you found any solution for this?

**Comment by dolanmiu** [comment]
@crossRT nope, gave up in the end

**Comment by niftylettuce** [comment]
As a former contributor to this package I strongly suggest everyone write pure Mongoose queries.

You can use two helper packages though which I wrote:

* Koa: https://github.com/koajs/ctx-paginate ([example here](https://github.com/koajs/ctx-paginate#example))
* Express: https://github.com/expressjs/express-paginate (for an example without Mongoose paginate refer to the [Koa example linked here](https://github.com/koajs/ctx-paginate#example))

**Comment by crossRT** [comment]
@dolanmiu too bad. it's okay.. =(
@niftylettuce alright, thanks. I'll have a look at it.

**Comment by niftylettuce** [comment]
I've updated the express-paginate README example to show an alternate simple solution to mongoose-paginate.

https://github.com/expressjs/express-paginate#example
