### ISSUE TITLE
Projections not working

### ISSUE THREAD

**Issue by imaustink** [edwardhotchkiss/mongoose-paginate#76]
Options.select is ignored and no projection is made.

**Comment by Jokero** [comment]
`mongoose-paginate` version? And example

**Comment by imaustink** [comment]
2.11.3

I was using it about like so:
``` javascript
var query = {
	$text: {
		$search: 'test',
		$language: 'en'
	}
};
var options = {
	page: 1,
	limit: 10,
	sort: {
		score: {
			$meta: 'textScore'
		}
	},
	select: {
		score: {
			$meta: 'textScore'
		}
	},
	lean: true,
	leanWithId: true
};

function callback(err, result){

}

Orders.paginate(query, options, callback);
```

No text score included in results
Also if you setup a blacklist projection it is ignored and all fields are still returned
And the lean flag is also being ignored. I don't get leaned records.

I have resulted to using Mongos native driver and it works like a charm.

**Comment by imaustink** [comment]
Shoot. I didn't realize it was Node 4.2+ now... I think my work machine is still on 0.12.x. Could this be related? Either way I am just going to the native driver.
