### ISSUE TITLE
get all results

### ISSUE THREAD

**Issue by alfredopacino** [edwardhotchkiss/mongoose-paginate#78]
hi, maybe it's a strange request:
how can I get all results using this module?
Basically a value for offset and limit I can be sure I get all results.

Thinking about it it's a pretty basic usage.
Otherwise I have to check the existence of those fields in query string and if they are not set I have to do a plain mongoose find().

**Comment by Kerumen** [comment]
Infinity will do the trick: `{ limit: Infinity, offset: 0 }`

**Comment by alfredopacino** [comment]
very thanks!

**Comment by Nox-404** [comment]
@Kerumen This doesn't work, it yeld : ```limit value must be non-negative```
