### ISSUE TITLE
Does page enumeration start at 1!?

### ISSUE THREAD

**Issue by ClaytonSmith** [edwardhotchkiss/mongoose-paginate#79]
Feeding `0` as a page number yields no docs but any page number above `1` will ( as long as there are docs for that page ). Is this a bug or intended feature?

**Comment by Jokero** [comment]
Yes, pagination starts with `page=1`

**Comment by ClaytonSmith** [comment]
What is the advantage of starting at `page=1` vs `page=0`?

**Comment by Jokero** [comment]
More logical to use `page=1`, just as in the real world with pagination. From the user perspective there is no zero page in UI, it always starts with 1. I have never seen that anywhere pagination starts with 0 :)

**Comment by Jokero** [comment]
For example, Github API https://developer.github.com/v3/#pagination

**Comment by jsonkody** [comment]
Nobody on earth starts counting from zero.
It's just some perversion of new programmers but in fact INDEXING from zero was a BIG mistake of old programmers and now its irreparable.
