### ISSUE TITLE
Mongoose Paginate doesn't work with replica set

### ISSUE THREAD

**Issue by mahelder** [edwardhotchkiss/mongoose-paginate#80]
Hello, I'm using this library with a single server of mongodb but, with a replica set, doesn't work.

Any idea?

**Comment by Jokero** [comment]
Try to do any request with `mongoose` only. If it does not work you should configure mongoose correctly

**Comment by mahelder** [comment]
Sorry, but I don't understand... 

my configuration of mongoose: 

```
mongoose.connect("mongodb://firstvm:27017,secondvm:27017,thirdvm:27017/mydb?replicaSet=myreplicaset");
db = mongoose.connection;
var mongoosePaginate = require('mongoose-paginate');

 var schema = new mongoose.Schema({
    prop1: String,
    prop2: Number,
    prop3: Number,
    prop4: { type: Boolean, default: true }
  }, { collection: 'test' });


schema.plugin(mongoosePaginate);

  return db.model('Pagination', schema);
```

My query: 
`return Model.paginate({}, { page: 3, limit: 10 });`

What do you want say with "request with mongoose"? Do you want say to do pagination without mongoose-pagination library?

**Comment by Jokero** [comment]
Do built-in mongoose methods work? What error do you get when call `Model.paginate`?

**Comment by Jokero** [comment]
Did you solve the problem?

**Comment by mahelder** [comment]
Sorry for the slow response ... I'm sure the problem is to solve ... my node version is 0.12.7 , I believe it was this ...
Thanks for attention
