### ISSUE TITLE
Paginate doesn't work within model

### ISSUE THREAD

**Issue by dacz** [edwardhotchkiss/mongoose-paginate#81]
I use paginate within my statics methods of the schema

```javascript
list: function list( options = {} ) {
    // some preparation ...
    return this.paginate( newOptions.query, newOptions.paginate );
  },
```

(I prefer to have model's functionality within models and not controllers)
I await on the promise once executed with await (within controller / tests).

But I get:

`TypeError: this.paginate is not a function`

All my other statics function can be called with `this`.

Am I missing something? Thanks!

**Comment by dacz** [comment]
To update:

I made it work with a hack: I do not activate is as a plugin but use it directly:

```
list: function list( options = {} ) {
    // some preparation ...
    return mongoosePaginate.paginate.call( this, newOptions.query, newOptions.paginate );
  },
```

But I'd prefer to use it as intended.

**Comment by Jokero** [comment]
I tried this and it works as expected:
```js
var BookSchema = new mongoose.Schema({
    title:  String,
    date:   Date,
    author: {
        type: mongoose.Schema.ObjectId,
        ref:  'Author'
    }
});

BookSchema.statics.list = function(query) {
    return this.paginate(query);
};

BookSchema.plugin(mongoosePaginate);

var Book = mongoose.model('Book', BookSchema);

Book.list().then(function(result) {
    // ...
});
```

**Comment by Jokero** [comment]
Did you solve the problem?

**Comment by dacz** [comment]
@Jokero I had no time to test it again so currently sticking with the solution I wrote. I'll get to it on the beginning of next week and write you. Thanks!
