### ISSUE TITLE
Will there be a typings file?

### ISSUE THREAD

**Issue by Cyber1000** [edwardhotchkiss/mongoose-paginate#82]
Hi,

I'm using your component, but I would like to use it a little bit more typesave.
I'm using typescript: Is there some typedefintion out there for mongoose-paginate(official/inofficial) or are you planning to provide one .d.ts-File?

Thanks!

**Comment by Jokero** [comment]
I don't use TypeScript, maybe typedefinition exists somewhere, I don't know)
I think you can try to create `.d.ts` file here https://github.com/DefinitelyTyped/DefinitelyTyped. As I see it's repository for TypeScript type definitions

**Comment by Cyber1000** [comment]
Thanks for your answer, I could even create a .d.ts in my project, but the problem is that I can't get a correct typedefintion for mongoose-paginate up and running. So I have to use an "any" type, which leverages the usage of not well-defined type-definitions. Ok perhaps someone other here has already written a .d.ts-file which works.

**Comment by tsm91** [comment]
@Cyber1000 Yeah that is a problem with typescript. The vast majority of libs does not have a well written external (ambient) type definition, if any at all.

maybe this one can get you started ( you will need `mongoose` ambient typing )

```typescript
///<reference path="../mongoose/mongoose.d.ts" />

declare module 'mongoose-paginate' {

  interface IOptions {
    select?: Object | string;
    sort?: Object | string;
    populate?: Array | Object | string;
    lean?: boolean;
    leanWithId?: boolean;
    offset?: number;
    page?: number;
    limit?: number;
  }

  interface IMongoosePaginate {
    (schema: Schema): any;
    paginate(query?: Object, options?: IOptions, callback?: (err: Object, result: any) => any): any;
  }

  const mongoosePaginate: IMongoosePaginate;
  export = mongoosePaginate;
}
```

@Jokero a lot of IDEs feed themselves with `.d.ts` files for IntelliSense. WebStorm too, in settings `Languages & Frameworks > JavaScript > Libraries`.

p.s: i don't use typescript but i do use these typings

**Comment by Splaktar** [comment]
The types are here:
https://www.npmjs.com/package/@types/mongoose-paginate

**Comment by MickL** [comment]
It should be noted that is only works when using `PaginateModel` instead of `Model`. Couldnt the types just extend `Model` so there is no need for another interface?
