### ISSUE TITLE
How to change pagination response object

### ISSUE THREAD

**Issue by monk8800** [edwardhotchkiss/mongoose-paginate#83]
Hi. 

How would you go about extending the plugin to change the response structure. Would like to add links e.g hasNext, hasPrevious and rename the fields such as docs to results without having to create an additional middleware

Would be great if someone can point me to the right direction.

**Comment by Jokero** [comment]
For now if you want to rename some fields you can do like this (if without creating middleware):
```js
Model.paginate().then(function(result) {
    const data = {
        results:     result.docs,
        hasNext:     result.docs.length + result.offset > result.total,
        hasPrevious: result.offset > 0
    };
});
```

But maybe it will be nice to have global for all `paginate` calls `transform` function:
```js
// somewhere in your config file

const mongoosePaginate = require('mongoose-paginate');

// you already can do so
mongoosePaginate.paginate.options = { 
  lean:  true,
  limit: 20
};

// transform function for all paginate calls
mongoosePaginate.paginate.transform = function(result) {
    return {
        results:     result.docs,
        hasNext:     result.docs.length + result.offset > result.total,
        hasPrevious: result.offset > 0
    };
};
```

And as result:
```js
Model.paginate().then(function(result) {
	/**
	 * result always has structure:
	 * { 
	 *   results: ..., 
	 *   hasNext: ..., 
	 *   hasPrevious: ... 
	 * }
	 */
});
```

What do you think @edwardhotchkiss, @monk8800?

**Comment by monk8800** [comment]
Looks good @Jokero the transform approach thanks for the hints

**Comment by Jokero** [comment]
`transform` function is not implemented, it's just my suggestion to add new feature to `mongoose-paginate`. I think it makes sense

**Comment by monk8800** [comment]
lol here i was getting excited, you got my vote

**Comment by niftylettuce** [comment]
PR welcome!

**Comment by ilaipi** [comment]
@Jokero thanks! 
nice solution except a little weight.
I only want to change 'docs' to 'rows', can I set a param in options.

```nodejs
import pagination from 'mongoose-paginate';
pagination.paginate.options = {
  docsKey: 'rows'
};
```
