### ISSUE TITLE
Mongo query error

### ISSUE THREAD

**Issue by CrackerakiUA** [edwardhotchkiss/mongoose-paginate#86]
After reinstall node_modules i am facing this error with our plugin. `MongoError: Can't canonicalize query: BadValue bad skip value in query`. Mongoose version is 4.4.14, node version is 5.11.0, mongoose-paginate version is latest on npm. I am just using empty object for query, and page and limit for options. `{},{page: 0, limit:3}`

**Comment by Jokero** [comment]
`page` starts from `1`. Maybe this is the reason

**Comment by CrackerakiUA** [comment]
Thank you, this is solved, issue was that i am using Collections from different databases.
