### ISSUE TITLE
Populate with SELCT

### ISSUE THREAD

**Issue by rhgithub1** [edwardhotchkiss/mongoose-paginate#88]
Hello all,
 is this capability already built? because I am able use POPULATE along with the PAGINATE but SELECT within the POPULATE is not working.

Thanks!

**Comment by rhgithub1** [comment]
found the answer myself. here is how you should use it

, populate: [{path:'yourjoinpath', select:"select1 select2"}]

**Comment by mitchellporter** [comment]
Here's a formatted example of the working solution:
```
var query = {};
query['populate'] = {path:'author', select:'-password -created_at -updated_at'}
```

**Comment by irshad-qb** [comment]
@mitchellporter I am using paginate plugin for a model with another model as ref. How can I query on the referencing model. I actually need search functionality. I need to do a regex search on the referencing BrandConfig model below. 

My models - 
`'use strict';
const mongoose = require('mongoose');
//Package to populate createdAt & updatedAt
const timestamps = require('mongoose-timestamp');
//Plugin for pagination support
const mongoosePaginate = require('mongoose-paginate');
const Schema = mongoose.Schema;

const brandConfigSchema = new Schema({
  brandName: {
    type: String,
    required: true,
    minLength: 1,
    unique: true
  },
  publishPath: {
    type: String,
    required: true,
    minLength: 1
  },
  damHost: {
    type: String,
    required: true,
    minLength: 1
  },
  operationType: {
    type: String,
    required: true,
    minLength: 3,
    default: 'normalApp'
  },
  serverConfigs: [{
    type: Schema.Types.ObjectId,
    ref: 'ServerConfig',
    required: true,
    minLength: 1
  }],
  userName: {
    type: String,
    required: true,
    minLength: 1
  },
  password: {
    type: String,
    required: true,
    minLength: 1
  },
  createdBy: {
    type: String,
    required: true,
    minLength: 1,
    default: 'admin'
  }
});

//plugin for auto population of createdAt & updatedAt
brandConfigSchema.plugin(timestamps);
brandConfigSchema.plugin(mongoosePaginate);
module.exports = mongoose.model('BrandConfig', brandConfigSchema, 'brandConfigs');`
