### ISSUE TITLE
Does this work with geospatial queries?

### ISSUE THREAD

**Issue by ihadeed** [edwardhotchkiss/mongoose-paginate#90]
Hey there,

Thank you for the awesome work here.

My application heavily depends on mongoose's `geoNear()` function to query for nearby places. Does your plugin `mongoose-paginate` have any support for that geospatial query function?

Thanks in advanced

**Comment by niftylettuce** [comment]
Have you tried it?

**Comment by ihadeed** [comment]
Tried and it didn't work. I'm just paginating manually, this plugin isn't
doing much after all. Uses skip&limit just like I would do.

**Comment by niftylettuce** [comment]
@ihadeed check out this cool example for the Koa version of express-paginate I made <https://github.com/koajs/ctx-paginate#example>
