### ISSUE TITLE
Is this plugin scalable?

### ISSUE THREAD

**Issue by vforv** [edwardhotchkiss/mongoose-paginate#92]
I found this answer on stackoverflow:

http://stackoverflow.com/questions/5539955/how-to-paginate-with-mongoose-in-node-js

> The cursor.skip() method is often expensive because it requires the server to walk from the beginning of the collection or index to get the offset or skip position before beginning to return result. As offset (e.g. pageNumber above) increases, cursor.skip() will become slower and more CPU intensive. With larger collections, cursor.skip() may become IO bound.

But I see in code is used skip() , so is this scalable?

**Comment by mitchellporter** [comment]
I'm curious about this as well.

**Comment by Jokero** [comment]
Hi! Do you have millions of documents? `skip` is really good when you need pagination. For most cases it's ok

**Comment by jmitch0901** [comment]
+1

**Comment by niftylettuce** [comment]
Yes it is scalable.  But if you are scaling to the size of Facebook then you might want to reconsider using something other than MongoDB and Mongoose.  Use the right tool for the job - this lets you iterate quickly.

**Comment by vforv** [comment]
Why MongoDB and Mongoose not good for big apps?
