### ISSUE TITLE
5.0.1 breaking

### ISSUE THREAD

**Issue by simlevesque** [edwardhotchkiss/mongoose-paginate#97]
On 5.0.0, everything worked, if I queried a collection that had data I received the docs array, but now I don't get it at all.

Sorry for the shitty issue, I'm in a hurry at work and I didn't have the time to deal with a minor update breaking my stuff.

**Comment by rclayton-the-terrible** [comment]
We're experiencing similar issues.

With the following query (I've replaced our actual entity name with `Model`):

```javascript
Model.paginate({}, { offset: 0, limit: 25, sort: { creationDate: -1 } }, (err, data) => {
      if (err) return callback(new InternalError(err));
      console.log('Response DATA:', data);
      return callback(null, {
        models: data.docs,
        pagination: omit(data, 'docs'),
      });
    });
```

The `console.log` statement prints:

```
Response DATA: { docs: undefined,
  total: undefined,
  limit: 25,
  offset: 0,
  page: 1,
  pages: 1 }
```

**Comment by niftylettuce** [comment]
I unpublished the build

**Comment by snypelife** [comment]
appears npm still has 5.0.1 as of 10:24am EDT. 
![screen shot 2016-09-30 at 10 24 59 am](https://cloud.githubusercontent.com/assets/1965406/18994965/33da1f66-86f8-11e6-94c2-a51b9d0efe5b.png)

**Comment by niftylettuce** [comment]
I contacted NPM to remove it manually, for some reason NPM CLI would not work for me.

**Comment by snypelife** [comment]
that's weird :/ ok, thanks for the update 👍

**Comment by niftylettuce** [comment]
They won't unpublish this, so I will be publishing v5.0.2 right now.

**Comment by Jokero** [comment]
You can publish tag 5.0.0 as 5.0.2

**Comment by niftylettuce** [comment]
@Jokero I'm giving you NPM owner access now as `jokero` on NPM to this package, I don't have time to maintain and I don't use it, sorry about this issue folks.
