### ISSUE TITLE
model.paginate returns docs UNDEFINED with version 5.0.2! Worked with earlier version

### ISSUE THREAD

**Issue by hamedordi** [edwardhotchkiss/mongoose-paginate#99]
Hi

My codes was working with version 5.0.0 until I updated to 5.0.2
'ModelSchema.paginate({refId': id}, {page: 1, limit: 1000}, function (err, result) {
      if (err)
        res.send(err);
      else
        res.json(result);
  });`

result is
`{"limit":"1000","page":"1","pages":1}`
result.doc is undefined
result.total is undefined

I run the same query with Model.Schema.find(..) and it works fine.
As I said it worked fine with version 5.0.0

node -v
v4.6.0

npm -v
2.15.9

mongoose version 4.4.20

Any idea what could be wronge?

Thanks for helping

**Comment by lukrizal** [comment]
+1

**Comment by Jokero** [comment]
I published 5.0.3 equivalent to 5.0.0. Try it.

My recommendation is to always use strict version of external packages in package.json

**Comment by maltheism** [comment]
I had the same issue on 5.0.2 but seems to be resolved with 5.0.3

**Comment by hamedordi** [comment]
thanks 

question, how did this pass the tests for v 5.0.2?

**Comment by Jokero** [comment]
5.0.2 is the result of a series of unfortunate events with this repository
